<?php
// $Id$

/**
 * @file
 * Installation hooks for headjs
 */

/**
 * Implementation of hook_install
 */
function headjs_install() {
  db_query("UPDATE {system} SET weight = 999 WHERE name = 'headjs'");
  cache_clear_all();
}

/**
 * Implementation of hook_uninstall().
 */
function headjs_uninstall() {
  variable_del('headjs_enable');
  variable_del('headjs_version');
  variable_del('headjs_path_full');
  variable_del('headjs_path_loader');
}
